import styles from "@/styles/404.module.scss";
import Head from "next/head";
import Image from "next/image";

//Image
import logo from "@/assets/iconsProject/logo.svg";
import Link from "next/link";

export default function error404() {
	return (
		<>
			<Head>
				<title>Fan Trade/Login</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.error404}>
				<Image
					src={logo}
					alt="logo"
					width={350}
					height={350}
					className={styles.error404__image}
					draggable={false}
				/>
				<div className={styles.error404__info}>
					<h1 className={styles.error404__info__title}>404</h1>
					<p className={styles.error404__info__article}>Page not foud</p>
					<button className={styles.error404__info__btn}>
						<Link href={"/"}> Return </Link>
					</button>
				</div>
			</div>
		</>
	);
}
