import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "@/styles/Home.module.scss";
import Link from "next/link";
import { useState } from "react";

//Image
import google from "@/assets/7611770.png";
import facebook from "@/assets/facebook.png";
import logo from "@/assets/iconsProject/logo.svg";

export default function Home() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const onHandleEmail = (e) => {
    setEmail(e.target.value);
  };

  const onHandlePassword = (e) => {
    setPassword(e.target.value);
  };

  const onHandleSubmit = (e) => {
    e.preventDefault();
    router.push("/HomePage");
  };
  return (
    <>
      <Head>
        <title>Fan Trade/Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.main__header}>
          <Image src={logo} alt="logo" width={70} height={70} />
          <h1 className={styles.main__header__title}>Funtrade</h1>
        </div>
        <div className={styles.main__login}>
          <h2 className={styles.main__login__title}>Accedi</h2>
          <form className={styles.main__login__form} onSubmit={onHandleSubmit}>
            <div className={styles.main__login__form__email}>
              <label for="email" className={styles.main__login__form__email__label}>
                Email
              </label>
              <input
                type="email"
                name="email"
                value={email}
                onChange={onHandleEmail}
                placeholder="Inserisci la tua email"
                required
                className={styles.main__login__form__email__input}
              />
            </div>
            <div className={styles.main__login__form__password}>
              <label for="password" className={styles.main__login__form__password__label}>
                Password
              </label>
              <input
                type="password"
                name="password"
                value={password}
                onChange={onHandlePassword}
                placeholder="**********"
                required
                className={styles.main__login__form__password__input}
              />
            </div>
            <input
              type="submit"
              name="submit"
              value="Accedi"
              className={styles.main__login__form__submit}
            />
          </form>
          <div className={styles.main__login__link}>
            <div className={styles.main__login__link__title}>
              <h3 className={styles.main__login__link__title__h3}>Oppure accedi con</h3>
            </div>
            <div className={styles.main__login__link__icons}>
              <Image src={google} alt="logo google" width={50} height={50} />
              <Image src={facebook} alt="logo google" width={50} height={50} />
            </div>
          </div>
          <div className={styles.main__login__sing_in}>
            <div className={styles.main__login__sing_in__title}>
              <h3 className={styles.main__login__sing_in__title__h3}>
                Non possiedi un account?
              </h3>
            </div>
            <button className={styles.main__login__sing_in__btn}>
              <Link href="/Iscriviti"> Iscriviti </Link>
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
