import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import NavbarBottom from "@/components/navbarBottom";
import NavbarTop from "@/components/navbarTop";
import { navbarItems } from "../mock/navbarItems";

export default function Home() {
  console.log(navbarItems);

  return (
    <>
      <Head>
        <title>Fan Trade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavbarTop items={navbarItems[0].items} />
        <h1>DREAM TEAM</h1>
        <NavbarBottom items={navbarItems[1].items} />
      </main>
    </>
  );
}
