import Head from "next/head";
import Link from "next/link";
/* import Navbar from "../components/Navbar"; */
import styles from "../styles/Profile.module.scss";
import MyBalance from "@/components/myBalance";
import UserAssets from "@/components/userAssets";

const Profile = () => {
  return (
    <>
      <Head>
        <title>Fan Trade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*  <Navbar /> */}
      <main className={`${styles.Profile}`}>
        <MyBalance />
        <div className={styles.__options}>
          <button>Negoziazioni</button>
          <button>Ordini</button>
          <button>Avvisi</button>
        </div>
        <UserAssets />
        <div className={styles.__functions}>
          <button>Preleva</button>
          <button>Deposita</button>
        </div>
      </main>
    </>
  );
};

export default Profile;
