import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Profile.module.scss";
import MyBalance from "@/components/myBalance";
import UserAssets from "@/components/userAssets";
import HistoryTransactions from "@/components/historyTransactions";

const Profile = () => {
  return (
    <>
      <Head>
        <title>Fan Trade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.Profile}`}>
        {/* Searchbar  */}
        <div className={styles.__container}>
          <div className={styles.__desktopLeftWrapper}>
            <MyBalance />
            <div className={styles.__options}>
              <button>Negoziazioni</button>
              <button>Ordini</button>
              <button>Avvisi</button>
            </div>
            <UserAssets />
            <div className={styles.__functions}>
              <button>Preleva</button>
              <button>Deposita</button>
            </div>
          </div>
          <div className={styles.__desktopRightWrapper}>
            <HistoryTransactions />
          </div>
        </div>
      </main>
    </>
  );
};

export default Profile;
