import Head from "next/head";
import Link from "next/link";

import DefaultLayout from "@/layouts/DefaultLayout";
import { useState } from "react";
import styles from "../styles/Profile.module.scss";
import MyBalance from "@/components/myBalance";
import UserAssets from "@/components/userAssets";
import HistoryTransactions from "@/components/historyTransactions";
import Search from "@/components/search";

const Profile = () => {
	return (
		<>
			<Head>
				<title>My Profile</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="../assets/iconsProject/favicon.ico" />
			</Head>
			<DefaultLayout>
				<main className={`${styles.Profile}`}>
					<div>{/* <Search /> */}</div>

					<div className={styles.__container}>
						<div className={styles.__desktopLeftWrapper}>
							<MyBalance />
							<div className={styles.__options}>
								<button>Negoziazioni</button>
								<button>Ordini</button>
								<button>Avvisi</button>
							</div>
							<UserAssets />
							<div className={styles.__functions}>
								<button>Preleva</button>
								<button>Deposita</button>
							</div>
						</div>
						<div className={styles.__desktopRightWrapper}>
							<HistoryTransactions />
							<div className={styles.__functionsRight}>
								<button>Preleva</button>
								<button>Deposita</button>
							</div>
						</div>
					</div>
				</main>
			</DefaultLayout>
		</>
	);
};

export default Profile;
